name: Go

on:
  push:
    branches:    
      - 'main'

jobs:

  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: |
          touch a.txt;
          echo "a=abc b=123 c=" > a.txt;
          echo "1" > a.txt;
          cat a.txt
    
       

    
